"""열거값 — docs/api.md §0.2 와 1:1. 문자열을 그대로 DB에 넣고 그대로 응답한다.

DB Enum 타입을 쓰지 않는 이유: 값이 한글이고, 마이그레이션 도구가 없어서
(구현계획 §7) 값 추가 때마다 DB를 갈아엎어야 하기 때문이다.
"""

CATEGORIES = ("학술·전공", "공연·예술", "체육", "봉사", "취미·교양", "종교")

RECRUIT_MOJIP = "모집중"
RECRUIT_CLOSED = "모집마감"
RECRUIT_ALWAYS = "상시모집"
RECRUIT_STATUSES = (RECRUIT_MOJIP, RECRUIT_CLOSED, RECRUIT_ALWAYS)

CLUB_ACTIVE = "활동중"
CLUB_ARCHIVED = "보관"
CLUB_STATUSES = (CLUB_ACTIVE, CLUB_ARCHIVED)

ACADEMIC_ENROLLED = "재학"
ACADEMIC_LEAVE = "휴학"
ACADEMIC_GRADUATED = "졸업"
ACADEMIC_STATUSES = (ACADEMIC_ENROLLED, ACADEMIC_LEAVE, ACADEMIC_GRADUATED)

ROLE_LEADER = "동아리장"
ROLE_MEMBER = "부원"
ROLES = (ROLE_LEADER, ROLE_MEMBER)

MEMBERSHIP_ACTIVE = "활동중"
MEMBERSHIP_OB = "OB"
MEMBERSHIPS = (MEMBERSHIP_ACTIVE, MEMBERSHIP_OB)

REQ_PENDING = "심사중"
REQ_APPROVED = "승인"
REQ_REJECTED = "거절"
REQ_CANCELLED = "취소"
REQUEST_STATUSES = (REQ_PENDING, REQ_APPROVED, REQ_REJECTED, REQ_CANCELLED)

GENDERS = ("남", "여")
